changeLogFile=src/main/resources/db/changelog/changelog-master.xml
url=jdbc:postgresql://localhost:5432/businessmng_db
username=businessmng_user
password=businessmng_password
driver=org.postgresql.Driver